### ISSUE TITLE
Not an issue - face filter reconn

### ISSUE THREAD

**Issue by 8secz-johndpope** [malayli/SwiftShaders#1]
I am shopping around for technology like snapchat face filters. Your repo comes up searching around ios code + glsl files. To be upfront - I've never written a shader.

So snapchat have a bunch of glsl shader files here - 
https://github.com/DeltaTheWolf/app-update-tracker/tree/cd6f0ed5cafa8cffaa148fe0fc5d16cfdec54a15/Snapchat/assets/looksery/core/scenarium

And config files that glue these pipelines together.
https://github.com/DeltaTheWolf/app-update-tracker/blob/cd6f0ed5cafa8cffaa148fe0fc5d16cfdec54a15/Snapchat/assets/looksery/lenses/content/pear_face/config.json

Could any of this code be dropped into an ios app?
Eg. If I wanted to import the  pear face filter - and have it work - would it need an army of staff to get working?

Shaders galore / can any of this be salvaged?
https://github.com/AloneMonkey/iOSREBook/tree/13728e7c036926420c51a1a028779e3c4a393c74/chapter-5/5.2%20%E5%8A%A8%E6%80%81%E8%B0%83%E8%AF%95/Snapchat/Snapchat.app/CoreResources.bundle/shaders

<img width="699" alt="Screen Shot 2019-10-31 at 2 06 27 pm" src="https://user-images.githubusercontent.com/50567111/67915595-a70a5480-fbe7-11e9-8854-b1ac61d46080.png">

**Comment by malayli** [comment]
Hello,

SwiftShaders only shows how to set a GLSL shader to a SceneKit node. First of all, I need to know if you want to use these GLSL shaders in SceneKit?

If yes, you will need to separate each file into a vertex file and a fragment file. So you can apply them to the SceneKit node shaderModifiers.

**Comment by 8secz-johndpope** [comment]
UPDATE - to answer your question - I actually don't need scenekit / am looking to load with camera.


Been doing some digging - consider with some effort - I believe it possible to load the glsl files dynamically rather than hard coding  or translating them.

This library has a couple of classes ShaderManager / 
https://github.com/c0g/FaceWarpApp

Thomas Gunter @c0g - any chance you could bump your stella repo to swift 4? 
or maybe help cherry pick the ShaderManager to work in swift 4? 

<img width="2317" alt="Screen Shot 2019-11-01 at 11 13 44 am" src="https://user-images.githubusercontent.com/50567111/67994313-b695a600-fc98-11e9-8e70-3476ca7fa5b4.png">


This code may have passed it's used by date - and not suitable for your project due to complexity integrating with scenekit - not sure. 

<img width="2560" alt="Screen Shot 2019-11-01 at 10 58 29 am" src="https://user-images.githubusercontent.com/50567111/67993802-97961480-fc96-11e9-81b8-0db492d22358.png">


I draw your attention to 

**TextureVertex.glsl**
```glsl 
attribute vec4 Position;
attribute vec2 TexSource;
attribute float InAlpha;
varying float Alpha;
varying vec2 UV;


void main(void) {
    UV = TexSource;
    Alpha = InAlpha;
    gl_Position = Position;
}


```

**TextureFragment.glsl**
```glsl
// Interpolated values from the vertex shaders
varying lowp vec2 UV;
varying lowp float Alpha;

// Values that stay constant for the whole mesh.
uniform sampler2D TextureSampler;

void main(){
    
    // Output color = color of the texture at the specified UV
    gl_FragColor = texture2D( TextureSampler, UV );
    gl_FragColor.a = Alpha;
}

```

in swift - to load this **TextureVertex**  and fragment - you just say
       ```swift
 passThroughShader = ShaderProgram(withVertexShader: "TextureVertex", andFragmentShader: "TextureFragment")!
        passThroughXYZ = GLuint(glGetAttribLocation(passThroughShader.programHandle, "Position"))
        passThroughUV = GLuint(glGetAttribLocation(passThroughShader.programHandle, "TexSource"))
        passThroughAlpha = GLuint(glGetAttribLocation(passThroughShader.programHandle, "InAlpha"))
        passThroughTex = GLint(glGetUniformLocation(passThroughShader.programHandle, "TextureSampler"))
        glEnableVertexAttribArray(passThroughXYZ)
        glEnableVertexAttribArray(passThroughUV)
```



Am I imaging it - or could a vast library of glsl shaders just be dropped into ios app like a gpuimage2 kind of sample of filters?
https://github.com/libretro/glsl-shaders/tree/8dc8e532fe582cda1ff49b3372411a644ad336df

**Comment by 8secz-johndpope** [comment]
I found this class that seems up to date - https://github.com/8secz-johndpope/iOS360Video/blob/master/360Video/Shader/GLProgram.swift

will attempt to drop in glsl shaders here.

**Comment by malayli** [comment]
Ok. I hope that it will work for you! @8secz-johndpope
